### ISSUE TITLE
Wrong win at the end of a round

### ISSUE THREAD

**Issue by AyukJason** [EHVAG/demoinfo#101]
When analysing the end of a round information for a win I have the following data output using the information in e.RoundEndReason and e.Winner.
Reason: TerroristWin, Winner: CounterTerrorist
Reason: Draw, Winner: Terrorist
Reason: Draw, Winner: Terrorist

This seems to be wrong. Can you explain why?

**Comment by moritzuehling** [comment]
I think the RoundWinReasons have changed recently.

**Comment by AyukJason** [comment]
Can you be more explicit

**Comment by AyukJason** [comment]
Also I have noticed that there are rounds which do not end

**Comment by moritzuehling** [comment]
That would be a seprate issue, and I need an example for that.

**Comment by AyukJason** [comment]
ok let me open an issue for that

**Comment by moritzuehling** [comment]
This has been fixed in #103
