### ISSUE TITLE
RoundOfficiallyEnd isn't called at match end.

### ISSUE THREAD

**Issue by RobinSverreBakker** [EHVAG/demoinfo#46]
Using the following code gives the following output on a demo that ended 16-11:

```
parser.RoundOfficiallyEnd += (sender, e) =>
{
    if (!hasMatchStarted)
        return;
    totalRounds++;
    Console.WriteLine(totalRounds + ": T " + parser.TScore + " - " + parser.CTScore + " CT");
};
```

![Output](http://i.imgur.com/zyglx5p.png)

As you can see, the twenty-seventh round isn't called, and as such neither is the 16-11 scoreline visible at that point. Running the same output command after parser.ParseToEnd(); does have the right scoreline.

**Comment by moritzuehling** [comment]
This is because the Event is just relayed from the GameEvents of the demo - there is nothing I can do about it, sorry.
