### ISSUE TITLE
Swag7

### ISSUE THREAD

**Issue by pawREP** [EHVAG/demoinfo#49]
Renaming the Mag-7 to Swag7 in EquipmentElements isn't the most user friendly thing to do. Took me a minute to find it.

**Comment by moritzuehling** [comment]
Hm, I'd rather have simply an additional entry in the enum, since else this would be a breaking change. I 'll do it if I have time, else I'm open for a pull-request

**Comment by pawREP** [comment]
Yes, adding another entry would do the trick. I also just noticed that the SG553 is wrongly label SG 556.

**Comment by littilesheep** [comment]
I'd like to use another enum, and I rename this weapon to JWag-7

**Comment by moritzuehling** [comment]
Closing after months of inactivity.
