### ISSUE TITLE
parser.RoundEnd fires to early

### ISSUE THREAD

**Issue by marinewater** [EHVAG/demoinfo#50]
You can see this easily in rounds where one team is eliminated:
The last killed guy will be shown as alive in `parser.PlayingParticipants` and still has the amount of HP he had before the last shot hit him.

**Comment by moritzuehling** [comment]
This is because GameEvents are networked before packet_entities-messages. 

The solution is that you "remember" that there was a RoundEnd-Event and do the work on the next TickDone event. Since this isn't an issue with the parser (but rather with the file-format) I'm closing this.
