### ISSUE TITLE
FileLoadException when trying to use Nuget Package in Visual Studio

### ISSUE THREAD

**Issue by marinewater** [EHVAG/demoinfo#57]
I get this error with the nuget package when trying to use demoinfo in Visual Studio:

```
An unhandled exception of type 'System.IO.FileLoadException' occurred in mscorlib.dll

Additional information: Could not load file or assembly 'DemoInfo, Version=1.0.0.0, Culture=neutral, PublicKeyToken=dc7de83c756ec63d' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)
```

**Comment by main--** [comment]
Quoting the [readme](https://github.com/EHVAG/demoinfo/blob/391710d977f4dc95c5d76248426eeeef38cc10a5/README.md#prereleases):

>Please note that the assemblies in these releases are **not** properly signed. They're [delay-signed](https://msdn.microsoft.com/en-us/library/t07a3dye.aspx) to ensure seamless compatibility with regular (stable) releases, but they don't carry a valid signature. This means that you *may* have to exclude `DemoInfo.dll` from strong name verification if you use these prereleases

#39 attempted to fix this, but we didn't find time (and/or a windows machine) to test it, so we ended up abandoning it.

You could test #39 and if it works, we could merge it to finally fix this issue.

Or you could just add the verification exemption yourself by running `sn -Vr path\to\DemoInfo.dll` in a visual studio command prompt.

**Comment by marinewater** [comment]
Thanks, the command worked, the NuGet package in the Pull Request did not.
