### ISSUE TITLE
Player_hurt event

### ISSUE THREAD

**Issue by 0BuRner** [EHVAG/demoinfo#58]
Hi,
Good news from last CSGO update (30 Juni) : 
```
– Added the player_hurt event to GOTV demos.
```
Can you implement it ?
Then we will be able to compute Efficacity like ESEA or CEVO :)

**Comment by hubwub** [comment]
I've been playing with the player_hurt event. Albeit not in C#, right now the values I've managed to get out of it are similar to this.

`    "player_hurt": {
        "params": {
            "armor": "byte", 
            "dmg_armor": "byte", 
            "weapon": "string", 
            "userid": "short", 
            "attacker": "short", 
            "dmg_health": "short", 
            "health": "byte", 
            "hitgroup": "byte"
        }, 
        "ID": 24, 
        "name": "player_hurt"
    }, 
`

But I have not been able to get anything out of hitgroup.

**Comment by econoraptor** [comment]
I was looking at this last night not even knowing about the valve update.  Assuming it works, I actually have the code written already I just need to check some things.  So hopefully I'll make a pull request later tonight.  Here's the available values as shown by valve's parser on an old demo:

descriptors {
  eventid: 24
  name: "player_hurt"
  keys {
    type: 4
    name: "userid"
  }
  keys {
    type: 4
    name: "attacker"
  }
  keys {
    type: 5
    name: "health"
  }
  keys {
    type: 5
    name: "armor"
  }
  keys {
    type: 1
    name: "weapon"
  }
  keys {
    type: 4
    name: "dmg_health"
  }
  keys {
    type: 5
    name: "dmg_armor"
  }
  keys {
    type: 5
    name: "hitgroup"
  }
}

**Comment by hubwub** [comment]
@econoraptor I'd used a demo post this update that was from FACEIT that was played today. However, I reached a point in which I was segfaulting, so I need to figure out why.

I also don't know if previous demos before this point will dump player_hurt. I'll have to check just in case.

**Comment by econoraptor** [comment]
From http://puppet-master.net/tutorials/source-engine/hitboxes-and-hitgroups/

HitGroups

0 = HITGROUP_GENERIC

1 = HITGROUP_HEAD

2 = HITGROUP_CHEST

3 = HITGROUP_STOMACH

4 = HITGROUP_LEFTARM

5 = HITGROUP_RIGHTARM

6 = HITGROUP_LEFTLEG

7 = HITGROUP_RIGHTLEG

10 = HITGROUP_GEAR

**Comment by moritzuehling** [comment]
Hey guys, 

I'm aware of this. I'll commit a working version of a parser that supports `player_hurt` in a few minutes.

**Comment by moritzuehling** [comment]
I have implemented this in 44413d817. The event works perfectly for me. If you have any questions or find bugs, you can open a new issue (or re-open this)
