### ISSUE TITLE
Player Rank

### ISSUE THREAD

**Issue by okankaya** [EHVAG/demoinfo#84]
Is it possible to parse player's rank from the demo, if yes, can this be added to the Player object?

**Comment by Calak** [comment]
This info is at the end of a MM (and only MM) demo.  
So,  it needs a complete parsing of the MM demo  before you can uses it.

**Comment by Calak** [comment]
This info is at the end of a MM (and only MM) demo.  
So,  it needs a complete parsing of the MM demo  before you can uses it.

**Comment by okankaya** [comment]
Thanks for the heads up.
