### ISSUE TITLE
detect impact location of bullet

### ISSUE THREAD

**Issue by clankill3r** [EHVAG/demoinfo#94]
I would to get the impact location of the bullets (when it hit's the walls etc.).
As far as I have seen something like that does not exist yet.

Would this be the right location to implement?
https://github.com/EHVAG/demoinfo/blob/master/DemoInfo/DP/Handler/GameEventHandler.cs#L120

**Comment by moritzuehling** [comment]
It would be the right location, if the data was saved in demofiles.

However, it isn't saved, so there is no way to do this properly.
